//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.plib {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtid;
		protected global::System.Web.UI.WebControls.TextBox txtpcode;
		protected global::System.Web.UI.WebControls.TextBox txtpname;
		protected global::System.Web.UI.WebControls.TextBox txtpdesc;
		protected global::System.Web.UI.WebControls.TextBox txtpleftcnt;
		protected global::System.Web.UI.WebControls.TextBox txtplupdatetime;
		protected global::System.Web.UI.WebControls.TextBox txtpsumcnt;
		protected global::System.Web.UI.WebControls.TextBox txtpsalecnt;
		protected global::System.Web.UI.WebControls.TextBox txtpls1;
		protected global::System.Web.UI.WebControls.TextBox txtpls2;
		protected global::System.Web.UI.WebControls.TextBox txtpls3;
		protected global::System.Web.UI.WebControls.TextBox txtpls4;
		protected global::System.Web.UI.WebControls.TextBox txtpls5;
		protected global::System.Web.UI.WebControls.TextBox txtpld1;
		protected global::System.Web.UI.WebControls.TextBox txtpld2;
		protected global::System.Web.UI.WebControls.TextBox txtpld3;
		protected global::System.Web.UI.WebControls.TextBox txtpld4;
		protected global::System.Web.UI.WebControls.TextBox txtpld5;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
