//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.plib {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblpcode;
	protected global::System.Web.UI.WebControls.Label lblpname;
	protected global::System.Web.UI.WebControls.Label lblpdesc;
	protected global::System.Web.UI.WebControls.Label lblpleftcnt;
	protected global::System.Web.UI.WebControls.Label lblplupdatetime;
	protected global::System.Web.UI.WebControls.Label lblpsumcnt;
	protected global::System.Web.UI.WebControls.Label lblpsalecnt;
	protected global::System.Web.UI.WebControls.Label lblpls1;
	protected global::System.Web.UI.WebControls.Label lblpls2;
	protected global::System.Web.UI.WebControls.Label lblpls3;
	protected global::System.Web.UI.WebControls.Label lblpls4;
	protected global::System.Web.UI.WebControls.Label lblpls5;
	protected global::System.Web.UI.WebControls.Label lblpld1;
	protected global::System.Web.UI.WebControls.Label lblpld2;
	protected global::System.Web.UI.WebControls.Label lblpld3;
	protected global::System.Web.UI.WebControls.Label lblpld4;
	protected global::System.Web.UI.WebControls.Label lblpld5;


       
    }
}
