//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.userlog {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtusercode;
		protected global::System.Web.UI.WebControls.TextBox txtuseraddr;
		protected global::System.Web.UI.WebControls.TextBox txtopertype;
		protected global::System.Web.UI.WebControls.TextBox txtoperobject;
		protected global::System.Web.UI.WebControls.TextBox txtopervalue;
		protected global::System.Web.UI.WebControls.TextBox txtoperdesc;
		protected global::System.Web.UI.WebControls.TextBox txtopertime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
