//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.product {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtpcode;
		protected global::System.Web.UI.WebControls.TextBox txtpname;
		protected global::System.Web.UI.WebControls.TextBox txtpsaleprice;
		protected global::System.Web.UI.WebControls.TextBox txtprealprice;
		protected global::System.Web.UI.WebControls.TextBox txtptype;
		protected global::System.Web.UI.WebControls.TextBox txtpisgroup;
		protected global::System.Web.UI.WebControls.TextBox txtpdesc;
		protected global::System.Web.UI.WebControls.TextBox txtps1;
		protected global::System.Web.UI.WebControls.TextBox txtps2;
		protected global::System.Web.UI.WebControls.TextBox txtps3;
		protected global::System.Web.UI.WebControls.TextBox txtps4;
		protected global::System.Web.UI.WebControls.TextBox txtps5;
		protected global::System.Web.UI.WebControls.TextBox txtpd1;
		protected global::System.Web.UI.WebControls.TextBox txtpd2;
		protected global::System.Web.UI.WebControls.TextBox txtpd3;
		protected global::System.Web.UI.WebControls.TextBox txtpd4;
		protected global::System.Web.UI.WebControls.TextBox txtpd5;
		protected global::System.Web.UI.WebControls.TextBox txtpdc1;
		protected global::System.Web.UI.WebControls.TextBox txtpdc2;
		protected global::System.Web.UI.WebControls.TextBox txtpdc3;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
