//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.product {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblpcode;
	protected global::System.Web.UI.WebControls.Label lblpname;
	protected global::System.Web.UI.WebControls.Label lblpsaleprice;
	protected global::System.Web.UI.WebControls.Label lblprealprice;
	protected global::System.Web.UI.WebControls.Label lblptype;
	protected global::System.Web.UI.WebControls.Label lblpisgroup;
	protected global::System.Web.UI.WebControls.Label lblpdesc;
	protected global::System.Web.UI.WebControls.Label lblps1;
	protected global::System.Web.UI.WebControls.Label lblps2;
	protected global::System.Web.UI.WebControls.Label lblps3;
	protected global::System.Web.UI.WebControls.Label lblps4;
	protected global::System.Web.UI.WebControls.Label lblps5;
	protected global::System.Web.UI.WebControls.Label lblpd1;
	protected global::System.Web.UI.WebControls.Label lblpd2;
	protected global::System.Web.UI.WebControls.Label lblpd3;
	protected global::System.Web.UI.WebControls.Label lblpd4;
	protected global::System.Web.UI.WebControls.Label lblpd5;
	protected global::System.Web.UI.WebControls.Label lblpdc1;
	protected global::System.Web.UI.WebControls.Label lblpdc2;
	protected global::System.Web.UI.WebControls.Label lblpdc3;


       
    }
}
