//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.pgroup {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtgid;
		protected global::System.Web.UI.WebControls.TextBox txtgindex;
		protected global::System.Web.UI.WebControls.TextBox txtgpid;
		protected global::System.Web.UI.WebControls.TextBox txtgpcnt;
		protected global::System.Web.UI.WebControls.TextBox txtgdesc;
		protected global::System.Web.UI.WebControls.TextBox txtgs1;
		protected global::System.Web.UI.WebControls.TextBox txtgs2;
		protected global::System.Web.UI.WebControls.TextBox txtgs3;
		protected global::System.Web.UI.WebControls.TextBox txtgs4;
		protected global::System.Web.UI.WebControls.TextBox txtgs5;
		protected global::System.Web.UI.WebControls.TextBox txtgd1;
		protected global::System.Web.UI.WebControls.TextBox txtgd2;
		protected global::System.Web.UI.WebControls.TextBox txtgd3;
		protected global::System.Web.UI.WebControls.TextBox txtgd4;
		protected global::System.Web.UI.WebControls.TextBox txtgd5;
		protected global::System.Web.UI.WebControls.TextBox txtgdc1;
		protected global::System.Web.UI.WebControls.TextBox txtgdc2;
		protected global::System.Web.UI.WebControls.TextBox txtgdc3;
		protected global::System.Web.UI.WebControls.TextBox txtgdc4;
		protected global::System.Web.UI.WebControls.TextBox txtgdc5;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
