//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.pgroup {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblgid;
	protected global::System.Web.UI.WebControls.Label lblgindex;
	protected global::System.Web.UI.WebControls.Label lblgpid;
	protected global::System.Web.UI.WebControls.Label lblgpcnt;
	protected global::System.Web.UI.WebControls.Label lblgdesc;
	protected global::System.Web.UI.WebControls.Label lblgs1;
	protected global::System.Web.UI.WebControls.Label lblgs2;
	protected global::System.Web.UI.WebControls.Label lblgs3;
	protected global::System.Web.UI.WebControls.Label lblgs4;
	protected global::System.Web.UI.WebControls.Label lblgs5;
	protected global::System.Web.UI.WebControls.Label lblgd1;
	protected global::System.Web.UI.WebControls.Label lblgd2;
	protected global::System.Web.UI.WebControls.Label lblgd3;
	protected global::System.Web.UI.WebControls.Label lblgd4;
	protected global::System.Web.UI.WebControls.Label lblgd5;
	protected global::System.Web.UI.WebControls.Label lblgdc1;
	protected global::System.Web.UI.WebControls.Label lblgdc2;
	protected global::System.Web.UI.WebControls.Label lblgdc3;
	protected global::System.Web.UI.WebControls.Label lblgdc4;
	protected global::System.Web.UI.WebControls.Label lblgdc5;


       
    }
}
