//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.clerk {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcname;
		protected global::System.Web.UI.WebControls.TextBox txtcphone;
		protected global::System.Web.UI.WebControls.TextBox txtcemail;
		protected global::System.Web.UI.WebControls.TextBox txtcsex;
		protected global::System.Web.UI.WebControls.TextBox txtclevel;
		protected global::System.Web.UI.WebControls.TextBox txtccode;
		protected global::System.Web.UI.WebControls.TextBox txtcaddress;
		protected global::System.Web.UI.WebControls.TextBox txtcsalesum;
		protected global::System.Web.UI.WebControls.TextBox txtcremark;
		protected global::System.Web.UI.WebControls.TextBox txtcls1;
		protected global::System.Web.UI.WebControls.TextBox txtcls2;
		protected global::System.Web.UI.WebControls.TextBox txtcls3;
		protected global::System.Web.UI.WebControls.TextBox txtcls4;
		protected global::System.Web.UI.WebControls.TextBox txtcls5;
		protected global::System.Web.UI.WebControls.TextBox txtcld1;
		protected global::System.Web.UI.WebControls.TextBox txtcld2;
		protected global::System.Web.UI.WebControls.TextBox txtcld3;
		protected global::System.Web.UI.WebControls.TextBox txtcld4;
		protected global::System.Web.UI.WebControls.TextBox txtcld5;
		protected global::System.Web.UI.WebControls.TextBox txtcldc1;
		protected global::System.Web.UI.WebControls.TextBox txtcldc2;
		protected global::System.Web.UI.WebControls.TextBox txtcldc3;
		protected global::System.Web.UI.WebControls.TextBox txtcldc4;
		protected global::System.Web.UI.WebControls.TextBox txtcldc5;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
