//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.clerk {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcname;
	protected global::System.Web.UI.WebControls.Label lblcphone;
	protected global::System.Web.UI.WebControls.Label lblcemail;
	protected global::System.Web.UI.WebControls.Label lblcsex;
	protected global::System.Web.UI.WebControls.Label lblclevel;
	protected global::System.Web.UI.WebControls.Label lblccode;
	protected global::System.Web.UI.WebControls.Label lblcaddress;
	protected global::System.Web.UI.WebControls.Label lblcsalesum;
	protected global::System.Web.UI.WebControls.Label lblcremark;
	protected global::System.Web.UI.WebControls.Label lblcls1;
	protected global::System.Web.UI.WebControls.Label lblcls2;
	protected global::System.Web.UI.WebControls.Label lblcls3;
	protected global::System.Web.UI.WebControls.Label lblcls4;
	protected global::System.Web.UI.WebControls.Label lblcls5;
	protected global::System.Web.UI.WebControls.Label lblcld1;
	protected global::System.Web.UI.WebControls.Label lblcld2;
	protected global::System.Web.UI.WebControls.Label lblcld3;
	protected global::System.Web.UI.WebControls.Label lblcld4;
	protected global::System.Web.UI.WebControls.Label lblcld5;
	protected global::System.Web.UI.WebControls.Label lblcldc1;
	protected global::System.Web.UI.WebControls.Label lblcldc2;
	protected global::System.Web.UI.WebControls.Label lblcldc3;
	protected global::System.Web.UI.WebControls.Label lblcldc4;
	protected global::System.Web.UI.WebControls.Label lblcldc5;


       
    }
}
