//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xwsw.Web.NMS.consumerservice {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtccode;
		protected global::System.Web.UI.WebControls.TextBox txtcphone;
		protected global::System.Web.UI.WebControls.TextBox txtcstype;
		protected global::System.Web.UI.WebControls.TextBox txtcsnum;
		protected global::System.Web.UI.WebControls.TextBox txtcsleft;
		protected global::System.Web.UI.WebControls.TextBox txtcsiostatus;
		protected global::System.Web.UI.WebControls.TextBox txtcstime0;
		protected global::System.Web.UI.WebControls.TextBox txtcstime1;
		protected global::System.Web.UI.WebControls.TextBox txtcstime2;
		protected global::System.Web.UI.WebControls.TextBox txtcstime3;
		protected global::System.Web.UI.WebControls.TextBox txtcstime4;
		protected global::System.Web.UI.WebControls.TextBox txtcstime5;
		protected global::System.Web.UI.WebControls.TextBox txtcstime6;
		protected global::System.Web.UI.WebControls.TextBox txtcstime7;
		protected global::System.Web.UI.WebControls.TextBox txtcstime8;
		protected global::System.Web.UI.WebControls.TextBox txtcstime9;
		protected global::System.Web.UI.WebControls.TextBox txtcstime10;
		protected global::System.Web.UI.WebControls.TextBox txtcss1;
		protected global::System.Web.UI.WebControls.TextBox txtcss2;
		protected global::System.Web.UI.WebControls.TextBox txtcss3;
		protected global::System.Web.UI.WebControls.TextBox txtcss4;
		protected global::System.Web.UI.WebControls.TextBox txtcss5;
		protected global::System.Web.UI.WebControls.TextBox txtcsd1;
		protected global::System.Web.UI.WebControls.TextBox txtcsd2;
		protected global::System.Web.UI.WebControls.TextBox txtcsd3;
		protected global::System.Web.UI.WebControls.TextBox txtcsd4;
		protected global::System.Web.UI.WebControls.TextBox txtcsd5;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
