//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xwsw.Web.NMS.consumerservice {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblccode;
	protected global::System.Web.UI.WebControls.Label lblcphone;
	protected global::System.Web.UI.WebControls.Label lblcstype;
	protected global::System.Web.UI.WebControls.Label lblcsnum;
	protected global::System.Web.UI.WebControls.Label lblcsleft;
	protected global::System.Web.UI.WebControls.Label lblcsiostatus;
	protected global::System.Web.UI.WebControls.Label lblcstime0;
	protected global::System.Web.UI.WebControls.Label lblcstime1;
	protected global::System.Web.UI.WebControls.Label lblcstime2;
	protected global::System.Web.UI.WebControls.Label lblcstime3;
	protected global::System.Web.UI.WebControls.Label lblcstime4;
	protected global::System.Web.UI.WebControls.Label lblcstime5;
	protected global::System.Web.UI.WebControls.Label lblcstime6;
	protected global::System.Web.UI.WebControls.Label lblcstime7;
	protected global::System.Web.UI.WebControls.Label lblcstime8;
	protected global::System.Web.UI.WebControls.Label lblcstime9;
	protected global::System.Web.UI.WebControls.Label lblcstime10;
	protected global::System.Web.UI.WebControls.Label lblcss1;
	protected global::System.Web.UI.WebControls.Label lblcss2;
	protected global::System.Web.UI.WebControls.Label lblcss3;
	protected global::System.Web.UI.WebControls.Label lblcss4;
	protected global::System.Web.UI.WebControls.Label lblcss5;
	protected global::System.Web.UI.WebControls.Label lblcsd1;
	protected global::System.Web.UI.WebControls.Label lblcsd2;
	protected global::System.Web.UI.WebControls.Label lblcsd3;
	protected global::System.Web.UI.WebControls.Label lblcsd4;
	protected global::System.Web.UI.WebControls.Label lblcsd5;


       
    }
}
