//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.piorecord {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtptime;
		protected global::System.Web.UI.WebControls.TextBox txtpcode;
		protected global::System.Web.UI.WebControls.TextBox txtpcnt;
		protected global::System.Web.UI.WebControls.TextBox txtpsaleprice;
		protected global::System.Web.UI.WebControls.TextBox txtprealprice;
		protected global::System.Web.UI.WebControls.TextBox txtptype;
		protected global::System.Web.UI.WebControls.TextBox txtpzekou;
		protected global::System.Web.UI.WebControls.TextBox txtpremark;
		protected global::System.Web.UI.WebControls.TextBox txtpguestid;
		protected global::System.Web.UI.WebControls.TextBox txtpsalerid;
		protected global::System.Web.UI.WebControls.TextBox txtpios1;
		protected global::System.Web.UI.WebControls.TextBox txtpios2;
		protected global::System.Web.UI.WebControls.TextBox txtpios3;
		protected global::System.Web.UI.WebControls.TextBox txtpios4;
		protected global::System.Web.UI.WebControls.TextBox txtpios5;
		protected global::System.Web.UI.WebControls.TextBox txtpiod1;
		protected global::System.Web.UI.WebControls.TextBox txtpiod2;
		protected global::System.Web.UI.WebControls.TextBox txtpiod3;
		protected global::System.Web.UI.WebControls.TextBox txtpiod5;
		protected global::System.Web.UI.WebControls.TextBox txtpiod4;
		protected global::System.Web.UI.WebControls.TextBox txtpiodc1;
		protected global::System.Web.UI.WebControls.TextBox txtpiodc2;
		protected global::System.Web.UI.WebControls.TextBox txtpiodc3;
		protected global::System.Web.UI.WebControls.TextBox txtpiodc4;
		protected global::System.Web.UI.WebControls.TextBox txtpiodc5;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
