//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.piorecord {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblptime;
	protected global::System.Web.UI.WebControls.Label lblpcode;
	protected global::System.Web.UI.WebControls.Label lblpcnt;
	protected global::System.Web.UI.WebControls.Label lblpsaleprice;
	protected global::System.Web.UI.WebControls.Label lblprealprice;
	protected global::System.Web.UI.WebControls.Label lblptype;
	protected global::System.Web.UI.WebControls.Label lblpzekou;
	protected global::System.Web.UI.WebControls.Label lblpremark;
	protected global::System.Web.UI.WebControls.Label lblpguestid;
	protected global::System.Web.UI.WebControls.Label lblpsalerid;
	protected global::System.Web.UI.WebControls.Label lblpios1;
	protected global::System.Web.UI.WebControls.Label lblpios2;
	protected global::System.Web.UI.WebControls.Label lblpios3;
	protected global::System.Web.UI.WebControls.Label lblpios4;
	protected global::System.Web.UI.WebControls.Label lblpios5;
	protected global::System.Web.UI.WebControls.Label lblpiod1;
	protected global::System.Web.UI.WebControls.Label lblpiod2;
	protected global::System.Web.UI.WebControls.Label lblpiod3;
	protected global::System.Web.UI.WebControls.Label lblpiod5;
	protected global::System.Web.UI.WebControls.Label lblpiod4;
	protected global::System.Web.UI.WebControls.Label lblpiodc1;
	protected global::System.Web.UI.WebControls.Label lblpiodc2;
	protected global::System.Web.UI.WebControls.Label lblpiodc3;
	protected global::System.Web.UI.WebControls.Label lblpiodc4;
	protected global::System.Web.UI.WebControls.Label lblpiodc5;


       
    }
}
