//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.serviceplan {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtid;
		protected global::System.Web.UI.WebControls.TextBox txtplandate;
		protected global::System.Web.UI.WebControls.TextBox txtplantime;
		protected global::System.Web.UI.WebControls.TextBox txttotalnum;
		protected global::System.Web.UI.WebControls.TextBox txtleftnum;
		protected global::System.Web.UI.WebControls.TextBox txtnexttotal;
		protected global::System.Web.UI.WebControls.TextBox txtnextleft;
		protected global::System.Web.UI.WebControls.TextBox txtnextid;
		protected global::System.Web.UI.WebControls.TextBox txtpss1;
		protected global::System.Web.UI.WebControls.TextBox txtpss2;
		protected global::System.Web.UI.WebControls.TextBox txtpss3;
		protected global::System.Web.UI.WebControls.TextBox txtpss4;
		protected global::System.Web.UI.WebControls.TextBox txtpss5;
		protected global::System.Web.UI.WebControls.TextBox txtpsd1;
		protected global::System.Web.UI.WebControls.TextBox txtpsd2;
		protected global::System.Web.UI.WebControls.TextBox txtpsd3;
		protected global::System.Web.UI.WebControls.TextBox txtpsd4;
		protected global::System.Web.UI.WebControls.TextBox txtpsd5;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
