//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.serviceplan {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblplandate;
	protected global::System.Web.UI.WebControls.Label lblplantime;
	protected global::System.Web.UI.WebControls.Label lbltotalnum;
	protected global::System.Web.UI.WebControls.Label lblleftnum;
	protected global::System.Web.UI.WebControls.Label lblnexttotal;
	protected global::System.Web.UI.WebControls.Label lblnextleft;
	protected global::System.Web.UI.WebControls.Label lblnextid;
	protected global::System.Web.UI.WebControls.Label lblpss1;
	protected global::System.Web.UI.WebControls.Label lblpss2;
	protected global::System.Web.UI.WebControls.Label lblpss3;
	protected global::System.Web.UI.WebControls.Label lblpss4;
	protected global::System.Web.UI.WebControls.Label lblpss5;
	protected global::System.Web.UI.WebControls.Label lblpsd1;
	protected global::System.Web.UI.WebControls.Label lblpsd2;
	protected global::System.Web.UI.WebControls.Label lblpsd3;
	protected global::System.Web.UI.WebControls.Label lblpsd4;
	protected global::System.Web.UI.WebControls.Label lblpsd5;


       
    }
}
