//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.userinfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txttagname;
		protected global::System.Web.UI.WebControls.TextBox txtemail;
		protected global::System.Web.UI.WebControls.TextBox txtlevel;
		protected global::System.Web.UI.WebControls.TextBox txtpwd;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtcreatetime;
		protected global::System.Web.UI.WebControls.TextBox txttoken;
		protected global::System.Web.UI.WebControls.TextBox txttokentime;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
