//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.servicerorder {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblccode;
	protected global::System.Web.UI.WebControls.Label lblspid;
	protected global::System.Web.UI.WebControls.Label lblspnum;
	protected global::System.Web.UI.WebControls.Label lblspspan;
	protected global::System.Web.UI.WebControls.Label lblsostatus;
	protected global::System.Web.UI.WebControls.Label lblcreatetime;
	protected global::System.Web.UI.WebControls.Label lblupdatetime;
	protected global::System.Web.UI.WebControls.Label lblupdateby;
	protected global::System.Web.UI.WebControls.Label lblsos1;
	protected global::System.Web.UI.WebControls.Label lblsos2;
	protected global::System.Web.UI.WebControls.Label lblsos3;
	protected global::System.Web.UI.WebControls.Label lblsos4;
	protected global::System.Web.UI.WebControls.Label lblsos5;
	protected global::System.Web.UI.WebControls.Label lblsod1;
	protected global::System.Web.UI.WebControls.Label lblsod2;
	protected global::System.Web.UI.WebControls.Label lblsod3;
	protected global::System.Web.UI.WebControls.Label lblsod4;
	protected global::System.Web.UI.WebControls.Label lblsod5;


       
    }
}
