//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.consumer {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcname;
		protected global::System.Web.UI.WebControls.TextBox txtccode;
		protected global::System.Web.UI.WebControls.TextBox txtcphone;
		protected global::System.Web.UI.WebControls.TextBox txtcemail;
		protected global::System.Web.UI.WebControls.TextBox txtclevel;
		protected global::System.Web.UI.WebControls.TextBox txtcsum;
		protected global::System.Web.UI.WebControls.TextBox txtcsex;
		protected global::System.Web.UI.WebControls.TextBox txtcremark;
		protected global::System.Web.UI.WebControls.TextBox txtcss1;
		protected global::System.Web.UI.WebControls.TextBox txtcss2;
		protected global::System.Web.UI.WebControls.TextBox txtcss3;
		protected global::System.Web.UI.WebControls.TextBox txtcss4;
		protected global::System.Web.UI.WebControls.TextBox txtcss5;
		protected global::System.Web.UI.WebControls.TextBox txtcsd1;
		protected global::System.Web.UI.WebControls.TextBox txtcsd2;
		protected global::System.Web.UI.WebControls.TextBox txtcsd3;
		protected global::System.Web.UI.WebControls.TextBox txtcsd4;
		protected global::System.Web.UI.WebControls.TextBox txtcsd5;
		protected global::System.Web.UI.WebControls.TextBox txtcsdc1;
		protected global::System.Web.UI.WebControls.TextBox txtcsdc2;
		protected global::System.Web.UI.WebControls.TextBox txtcsdc3;
		protected global::System.Web.UI.WebControls.TextBox txtcsdc4;
		protected global::System.Web.UI.WebControls.TextBox txtcsdc5;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
