//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.consumer {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcname;
	protected global::System.Web.UI.WebControls.Label lblccode;
	protected global::System.Web.UI.WebControls.Label lblcphone;
	protected global::System.Web.UI.WebControls.Label lblcemail;
	protected global::System.Web.UI.WebControls.Label lblclevel;
	protected global::System.Web.UI.WebControls.Label lblcsum;
	protected global::System.Web.UI.WebControls.Label lblcsex;
	protected global::System.Web.UI.WebControls.Label lblcremark;
	protected global::System.Web.UI.WebControls.Label lblcss1;
	protected global::System.Web.UI.WebControls.Label lblcss2;
	protected global::System.Web.UI.WebControls.Label lblcss3;
	protected global::System.Web.UI.WebControls.Label lblcss4;
	protected global::System.Web.UI.WebControls.Label lblcss5;
	protected global::System.Web.UI.WebControls.Label lblcsd1;
	protected global::System.Web.UI.WebControls.Label lblcsd2;
	protected global::System.Web.UI.WebControls.Label lblcsd3;
	protected global::System.Web.UI.WebControls.Label lblcsd4;
	protected global::System.Web.UI.WebControls.Label lblcsd5;
	protected global::System.Web.UI.WebControls.Label lblcsdc1;
	protected global::System.Web.UI.WebControls.Label lblcsdc2;
	protected global::System.Web.UI.WebControls.Label lblcsdc3;
	protected global::System.Web.UI.WebControls.Label lblcsdc4;
	protected global::System.Web.UI.WebControls.Label lblcsdc5;


       
    }
}
