//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.historyalarm {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtalarmname;
		protected global::System.Web.UI.WebControls.TextBox txtalarmdesc;
		protected global::System.Web.UI.WebControls.TextBox txtcreatetime;
		protected global::System.Web.UI.WebControls.TextBox txtupdatetime;
		protected global::System.Web.UI.WebControls.TextBox txtownerid;
		protected global::System.Web.UI.WebControls.TextBox txthandlerid;
		protected global::System.Web.UI.WebControls.TextBox txtalarmtype;
		protected global::System.Web.UI.WebControls.TextBox txtoperateid;
		protected global::System.Web.UI.WebControls.TextBox txthandlestatus;
		protected global::System.Web.UI.WebControls.TextBox txtconfirmtime;
		protected global::System.Web.UI.WebControls.TextBox txthandledetail;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
