//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jium.Web.historyalarm {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblalarmname;
	protected global::System.Web.UI.WebControls.Label lblalarmdesc;
	protected global::System.Web.UI.WebControls.Label lblcreatetime;
	protected global::System.Web.UI.WebControls.Label lblupdatetime;
	protected global::System.Web.UI.WebControls.Label lblownerid;
	protected global::System.Web.UI.WebControls.Label lblhandlerid;
	protected global::System.Web.UI.WebControls.Label lblalarmtype;
	protected global::System.Web.UI.WebControls.Label lbloperateid;
	protected global::System.Web.UI.WebControls.Label lblhandlestatus;
	protected global::System.Web.UI.WebControls.Label lblconfirmtime;
	protected global::System.Web.UI.WebControls.Label lblhandledetail;


       
    }
}
